function Venus_DataToR_v3(varargin)

% Convert MAT file outputs generated by Venus experiment into a text file for processing in R
% Example: Venus_DataToR_v3('matFileName=stim_0106.mat', 'subjectID=IMJ', 'sessionNumber=5')

% Parse input parameters. Assign defaults to parameters that haven't been
% assigned through varargin

% 15 May 2013, Arman
% -- Added saving reaction time data

[dataForR] = parseArgs(varargin);

if isempty(dataForR.matFileName)
    disp(sprintf('(DataToR) Please specity MAT file name'));
    return;
end
if isempty(dataForR.subjectID)
    disp(sprintf('(DataToR) Please specify subjectID'));
    return;
end
if isempty(dataForR.sessionNumber)
    disp(sprintf('(DataToR) Please specify sessionNumber'));
    return;
end
% Read the MAT file
load(dataForR.matFileName);
vars = getTaskParameters(myscreen, task);
vars = cellArray(vars);
% This is adjustment due to different formats of 
% "task" variable. Sometimes it is cell array containing arrays
% Other times it is an array of cells
if size(task, 2) == 1 task = task{1}; end
nTrials = vars{1}(2).nTrials;
% This variable contains contrast intensity, visual field and drift in the
% order they were presented in the experiment
stimOrder = task{2}.randVars.stimRandomOrder(1:nTrials,:);  
% Fill out necessary data from the experiment
dataForR.contrastIntensity = task{2}.parameter.intensities(stimOrder(:, 1))';   % Get actual contrast intensities instead of their indices
dataForR.visualField = stimOrder(:, 2);                                         % Left visual fiels is coded as 1, right VF is coded as 2
dataForR.driftOrientation = stimOrder(:, 3);                                    % left drift is coded as 1, right drift is coded as 2
% Get reaction time
dataForR.reactionTime = reshape(vars{1}(2).reactionTime, nTrials, 1);
% Get exp date and start time
[dataForR.collectionDate dataForR.collectionTime] = strtok(myscreen.starttime);
% To fill out a column, replicate date and time to match the number of trials
dataForR.collectionDate = repmat(dataForR.collectionDate, nTrials, 1);
dataForR.collectionTime = repmat(dataForR.collectionTime, nTrials, 1);
% Subject responses
dataForR.subjectResponse = reshape(vars{1}(2).response, nTrials, 1);
% Do the same with subjectID and sessionNumber
dataForR.subjectID = repmat(dataForR.subjectID, nTrials, 1);
dataForR.sessionNumber = repmat(dataForR.sessionNumber, nTrials, 1);
% Change the extension of the mat file into TXT to save the data
[fileName extenstion] = strtok(dataForR.matFileName, '.');
outputFileName = [fileName '.txt'];
% Check if the file doesn't exist
if ~exist(outputFileName)
    disp(sprintf('(DataToR) Writing data to %s', [pwd '/' outputFileName]));
    % First, names of columns
    outputData1 = ['SubjectID', ',', 'SessionID', ',', 'Date', ',', 'Time', ',', 'Contrast', ',', 'VisualField', ',', 'Drift', ',', 'Response', ',', 'RT', char(10)];
    % Now data
    outputData2 = [dataForR.subjectID, repmat(',', nTrials, 1), ...
        num2str(dataForR.sessionNumber), repmat(',', nTrials, 1), ...
        dataForR.collectionDate, repmat(',', nTrials, 1), ...;
        dataForR.collectionTime, repmat(',', nTrials, 1), ...
        num2str(dataForR.contrastIntensity), repmat(',', nTrials, 1), ...
        num2str(dataForR.visualField), repmat(',', nTrials, 1), ...
        num2str(dataForR.driftOrientation), repmat(',', nTrials, 1), ...
        num2str(dataForR.subjectResponse), repmat(',', nTrials, 1), ...
        num2str(dataForR.reactionTime), ...
        repmat(char(10),nTrials, 1)];
    % Save into a file
    fileID = fopen(outputFileName,'w');
    fprintf(fileID,'%s', outputData1');
    fprintf(fileID,'%s', outputData2');
    fclose (fileID);
else
    disp(sprintf('(DataToR) File named %s already exists. Rename or delete, then run again', outputFileName));
end


%********************************************
% parseArgs
function [dataForR] = parseArgs(args)

success = 1;
% Set arguments based on passed parameters. The rest will be set to defaults. 
getArgs(args,{ ...
    'matFileName=[]',...                   % Name of the data file
    'subjectID=[]', ...                % Subject ID
    'sessionNumber=', ...                   % Consequtive number of the session
    'collectionDate=[]', ...                % Data collection day
    'collectionTime=[]', ...                % Data collection time
    'contrastIntensity=[]', ...             % Intensity of the contrast
    'visualField=[]', ...                   % Left or right VF
    'driftOrientation=[]', ...              % Drifting orientation of the grating
    'stimulusDuration=[]', ...              % Stimulus presentation time
    'outputFileName=[]', ...                % Name of text file to save the output
    'subjectResponse=[]', ...               % Subject responses
    });
% Pack all arguments into a structure            
dataForR.matFileName = matFileName;
dataForR.subjectID = subjectID;
dataForR.sessionNumber = sessionNumber;
dataForR.collectionDate = collectionDate;
dataForR.collectionTime = collectionTime;
dataForR.contrastIntensity = contrastIntensity;
dataForR.visualField = visualField;
dataForR.driftOrientation = driftOrientation;
dataForR.stimulusDuration = stimulusDuration; 
dataForR.outputFileName = outputFileName; 
dataForR.subjectResponse = subjectResponse;



